//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SCC
//  @ File Name : Login.cs
//  @ Date : 7/24/2012
//  @ Author : 
//
//


namespace ComprasColetivas.Domain.Model
{

    public class Login
    {
        public Pessoa pessoa;

        public Login(Pessoa pessoa)
        {
            this.pessoa = pessoa;
        }
    }
}